nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['.*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'X-API-KEY']
        expose_headers: ['Link', 'X-Total-Count', 'X-Page-Count', 'X-Error-Message', 'Content-Type']
        max_age: 86400
        allow_credentials: true
        forced_allow_origin_value: ~
    paths:
        '^/api/': 
            origin_regex: true
            allow_origin: ['.*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'X-API-KEY']
            expose_headers: ['Link', 'X-Total-Count', 'X-Page-Count', 'X-Error-Message', 'Content-Type']
            max_age: 86400
            allow_credentials: true
